models.py
import datetime
from flask_admin.contrib.mongoengine import ModelView
from misc.init import db
from misc.utils import generate_id


class PlanModel(db.Document):
    name = db.StringField(required=True, max_length=200, min_length=3, unique=True)
    created_at = db.DateTimeField(default=datetime.datetime.now())
    short_description = db.StringField(max_length=2000, min_length=3)
    plan_id = db.StringField(required=True, max_length=30, min_length=3, default=generate_id(45))
    features = db.ListField(db.StringField(max_length=2000))
    price = db.StringField(required=True, max_length=10, min_length=3)


class ProductsModel(db.Document):
    name = db.StringField(required=True, max_length=200, min_length=3, unique=True)
    created_at = db.DateTimeField(default=datetime.datetime.now())
    description = db.StringField(max_length=2000, min_length=3)
    product_id = db.StringField(required=True, max_length=30, min_length=3)
    features = db.ListField(db.StringField(max_length=2000))
    price = db.StringField(required=True, max_length=10, min_length=3)


class NormanModelView(ModelView):
    def is_accessible(self):
        return True

misc/app.py
from flask.helpers import get_debug_flag

from misc.app_tools import create_app
from config import ProdConfig, DevConfig


CONFIG = DevConfig if get_debug_flag() else ProdConfig


app = create_app(CONFIG)

views/demo.py
from flask import Blueprint
from flask import render_template

blueprint = Blueprint('demo', __name__,url_prefix='/auth/request/demo', static_folder='../static')


@blueprint.route('/')
def demoAuth():
    return render_template('auth/login.html')

views/landing.py
from flask import Blueprint, render_template
from flask import templating
# from security import norman_security

blueprint = Blueprint('public', __name__, static_folder='../static')


@blueprint.route('/', methods=['GET'])
def home():
    return render_template('index.html')


@blueprint.route('/privacy', methods=['GET'])
def privacy():
    return render_template('privacy.html')


@blueprint.route('/pricing', methods=['GET'])
def pricing():
    return render_template('pricing.html')


@blueprint.route('/faq', methods=['GET'])
def faq():
    return render_template('faq.html')


@blueprint.route('/hospital', methods=['GET'])
def hospital():
    return render_template('single-hospital.html')


@blueprint.route('/request-demo', methods=['GET'])
def demoRequest():
    return render_template('demo.html')


@blueprint.route('/features', methods=['GET'])
def features():
    return render_template('features.html')


@blueprint.route('/knowledge-base', methods=['GET'])
def knowledge():
    return render_template('knowledge.html')

views/login.py
from flask import Blueprint, render_template
# from security import norman_security

blueprint = Blueprint('login', __name__,url_prefix='/auth/login', static_folder='../static')


@blueprint.route('/')
def loginAuth():
    return render_template('auth/login.html')

views/products.py
from flask import Blueprint, render_template

blueprint = Blueprint('product', __name__, url_prefix='/products', static_folder='../static')


@blueprint.route('/', methods=['GET'])
def products():
    return render_template('index.html')


@blueprint.route('/bot', methods=['GET'])
def bot():
    return render_template('bot.html')


@blueprint.route('/analytics', methods=['GET'])
def analytics():
    return render_template('analytics.html')


@blueprint.route('/collate', methods=['GET'])
def collate():
    return render_template('collate.html')


@blueprint.route('/ipatient', methods=['GET'])
def ipatient():
    return render_template('patient.html')


@blueprint.route('/ihealth', methods=['GET'])
def ihealth():
    return render_template('health.html')


@blueprint.route('/idoctor', methods=['GET'])
def idoctor():
    return render_template('collate.html')

views/register.py
from datetime import datetime

from flask import Blueprint, render_template, jsonify
from flask import request


blueprint = Blueprint('register', __name__,url_prefix='/auth/register', static_folder='../static')


@blueprint.route('/')
def planOrProduct():
    return render_template('auth/planOrChoice.html')


@blueprint.route('/preRegistration')
def preRegistration():
    option = request.args.get('option')
    if option == 'plan':
        return render_template('auth/configurePlan.html')
    return render_template('auth/configureProduct.html')


@blueprint.route('/initRegistration')
def initRegistration():
    option = request.args.get('option')
    if option == 'plan':
        plan = request.args.get('plan')
        return render_template('auth/initRegistration.html')
    return render_template('auth/configureProduct.html')

templates/analytics.html
{% include 'shared/header.html' %}


    <div class="content-wrapper oh">

      <!-- Hero -->
      <section class="hero bg-green">
        <div class="container hero__container hero__container--720">

          <div class="row hero__outer flex-vertical-align-center">
            <div class="col-md-12 mt-50 text-center hidden-sm hidden-xs">
              <img src="{{ url_for('static', filename='img/hero/norman_dashboard_edited.png') }}" style="height: 500%; width: 100%" alt="">
            </div>
            <div class="col-lg-5 col-lg-offset-2 col-md-5 col-xs-12">
              <div class="optin optin--mt-minus-30 text-center">
                <h1 class="optin__title">Conveniently collate and analyze your patient data.</h1>
                <form class="optin__form">
                  <button href="javascript:handleAjaxRoute('auth/register', {'source':'landingPage'})" class="optin__btn btn btn--lg btn--color btn--wide btn--button square">Register</button>
                </form>
              </div>
            </div>
          </div>

        </div>
      </section> <!-- end hero -->

      <!-- Video -->
      <section class="section-wrap bg-light bottom-divider" id="video">
        <div class="container text-center">
          <div class="row">
            <div class="col-md-8 col-md-offset-2">
              <div class="embed-responsive embed-responsive-16by9">
                <iframe src="https://www.youtube.com/embed/ScMzIvxBSi4?showinfo=0" class="embed-responsive-item"></iframe>
              </div>
              <span class="video-caption">Quick Norman Overview.</span>
            </div>
          </div>
        </div>
      </section> <!-- end video-section -->


      <!-- Benefits -->
      <section class="section-wrap pb-100" id="benefits">
        <div class="container">
          <div class="heading-row text-center">
            <h2 class="heading">Here's a sneak peek of what Norman Analytics offers you</h2>
          </div>
          <div class="row">

            <div class="col-sm-6">
                <div class="col-sm-6 mb-sm-40">
                {% for feature, description in config.NORMAN_FEATURES_LEFT.items() %}
              <div class="benefit">
                <i class="benefit__icon ui-check"></i>
                <p class="benefit__text lead">{{ description.description }}</p>
              </div>
                {% endfor %}
            </div> <!-- end col -->



            <div class="col-sm-6 mb-sm-40">
                {% for feature, description in config.NORMAN_FEATURES_RIGHT.items() %}
              <div class="benefit">
                <i class="benefit__icon ui-check"></i>
                <p class="benefit__text lead">{{ description.description }}</p>
              </div>
                {% endfor %}
            </div> <!-- end col -->

          </div>
        </div>
      </section> <!-- end benefits -->

      <section class="section-wrap bg-light bottom-divider" id="testimonials">
        <div class="container">
          <div class="heading-row text-center">
            <h2 class="heading">Those who already tried it</h2>
          </div>

          <div class="row">

            <div id="owl-testimonials" class="owl-carousel owl-theme">

              <div class="testimonial__wrap">
                <div class="testimonial box-shadow text-center clearfix">
                  <img src="{{ url_for('static', filename='img/testimonials/1.jpg') }}" alt="" class="testimonial__img">
                  <div class="testimonial__body">
                    <p class="testimonial__text">“I’am amazed, I should say thank you so much for your awesome template. Design is so good and neat.”</p>
                  </div>
                  <div class="testimonial__info">
                    <span class="testimonial__author">Christine Clark</span>
                    <span class="testimonial__company">DeoThemes</span>
                  </div>
                </div>
              </div>

              <div class="testimonial__wrap">
                <div class="testimonial box-shadow text-center clearfix">
                  <img src="{{ url_for('static', filename='img/testimonials/2.jpg') }}" alt="" class="testimonial__img">
                  <div class="testimonial__body">
                    <p class="testimonial__text">“Every detail has been taken care these team are realy amazing and talented! I will work only with emaus agency.”</p>
                  </div>
                  <div class="testimonial__info">
                    <span class="testimonial__author">Mark Zukerberg</span>
                    <span class="testimonial__company">Facebook</span>
                  </div>
                </div>
              </div>

              <div class="testimonial__wrap">
                <div class="testimonial box-shadow text-center clearfix">
                  <img src="{{ url_for('static', filename='img/testimonials/3.jpg') }}" alt="" class="testimonial__img">
                  <div class="testimonial__body">
                    <p class="testimonial__text">“I have witnessed and admired the work for years. I highly recommend this work for anyone seeking to increase.”</p>
                  </div>
                  <div class="testimonial__info">
                    <span class="testimonial__author">Alex Samokhin</span>
                    <span class="testimonial__company">Alphabet</span>
                  </div>
                </div>
              </div>

              <div class="testimonial__wrap">
                <div class="testimonial box-shadow text-center clearfix">
                  <img src="{{ url_for('static', filename='img/testimonials/1.jpg') }}" alt="" class="testimonial__img">
                  <div class="testimonial__body">
                    <p class="testimonial__text">“I’am amazed, I should say thank you so much for your awesome template. Design is so good and neat.”</p>
                  </div>
                  <div class="testimonial__info">
                    <span class="testimonial__author">Christine Clark</span>
                    <span class="testimonial__company">DeoThemes</span>
                  </div>
                </div>
              </div>

              <div class="testimonial__wrap">
                <div class="testimonial box-shadow text-center clearfix">
                  <img src="{{ url_for('static', filename='img/testimonials/2.jpg') }}" alt="" class="testimonial__img">
                  <div class="testimonial__body">
                    <p class="testimonial__text">“Every detail has been taken care these team are realy amazing and talented! I will work only with emaus agency.”</p>
                  </div>
                  <div class="testimonial__info">
                    <span class="testimonial__author">Mark Zukerberg</span>
                    <span class="testimonial__company">Facebook</span>
                  </div>
                </div>
              </div>

            </div> <!-- end of slider -->

          </div>
        </div>
      </section> <!-- end testimonials -->


{% include 'shared/newsletter.html' %}

{% include 'shared/footer.html' %}

templates/collate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/faq.html
{% include 'shared/header.html' %}

      <section class="section-wrap pb-90" id="faq">
        <div class="container">
          <div class="heading-row text-center">
            <h2 class="heading">Frequently asked questions</h2>
          </div>
          <div class="row">

            <div class="col-sm-5 col-sm-offset-1">
              <h4 class="faq__title">14-day trial</h4>
              <p class="faq__text">Our Theme is a very slick and clean e-commerce template with endless possibilities. Creating an awesome website with this Theme is easy than you can imagine. Our Theme is a very slick and clean e-commerce template.</p>

              <h4 class="faq__title">Recovering an expired account</h4>
              <p class="faq__text">Our Theme is a very slick and clean e-commerce template with endless possibilities. Creating an awesome website with this Theme is easy than you can imagine. Our Theme is a very slick and clean e-commerce template.</p>
            </div>

            <div class="col-sm-5">
              <h4 class="faq__title">Payments</h4>
              <p class="faq__text">Our Theme is a very slick and clean e-commerce template with endless possibilities. Creating an awesome website with this Theme is easy than you can imagine. Our Theme is a very slick and clean e-commerce template.</p>

              <h4 class="faq__title">Canceling subscription</h4>
              <p class="faq__text">Our Theme is a very slick and clean e-commerce template with endless possibilities. Creating an awesome website with this Theme is easy than you can imagine. Our Theme is a very slick and clean e-commerce template.</p>
            </div>

          </div>
        </div>
      </section> <!-- end faq -->

      {% include 'shared/newsletter.html' %}

{% include 'shared/footer.html' %}

templates/index.html
{% include 'shared/header.html' %}

    <div class="content-wrapper oh">

      <!-- Hero -->
      <section class="hero bg-img bg-gradient white-text" style="background-image: url({{ url_for('static', filename='img/hero/reception.jpg') }});">

        <div class="container  hero__container container-full-height">

     <div class="row hero__outer flex-vertical-align-center">
            <div class="col-md-12">
              <h1 class="hero__title full-view">{{ config.MAIN_UI_TEXT }}</h1>
              <div class="hero__btn-holder mt-30">
                <a href="{{ url_for('register.planOrProduct') }}" class="btn btn--lg btn--color square"><span>Sign Up</span></a>
                <div class="play-btn__wrap">
                  <a href="https://www.youtube.com/watch?v=nVzVohG304A?autoplay=1" class="play-btn play-btn--sm play-btn--white single-video-lightbox"></a>
                  <span class="play-btn__text">How it Works</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section> <!-- end hero -->

      <!-- Partners -->
      <section class="partners text-center bottom-divider">
        <div class="container">
          <div class="row">

            <div class="col-sm-5ths col-xs-3 col-xxs-6">
              <a href="#">
                <img src="{{ url_for('static', filename='img/partners/techpoint.png') }}" alt="">
              </a>
            </div>
            <div class="col-sm-5ths col-xs-3 col-xxs-6">
              <a href="#">
                <img src="{{ url_for('static', filename='img/partners/techcabal.png') }}" alt="">
              </a>
            </div>
            <div class="col-sm-5ths col-xs-3 col-xxs-6">
              <a href="#">
                <img src="{{ url_for('static', filename='img/partners/techarewa.png') }}" alt="">
              </a>
            </div>
          </div>
        </div>
      </section> <!-- end partners -->
      <!-- Intro -->
      <section class="section-wrap bottom-divider">
        <div class="container">
          <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center">
              <span class="intro__subtitle uppercase">{{ config.MAIN_UI_TEXT }}</span>
              <h2 class="intro__title">
                {{ config.SECTION_TWO_INFO }}
              </h2>
            </div>
          </div>
        </div>
      </section> <!-- end intro -->

      <!-- Promo Section -->
      <section class="section-wrap promo-section bottom-divider pb-100">
        <div class="container ">
          <div class="row flex-parent flex-vertical-align-center flex-sm-collapse">
               <div class="col-md-6 col-sm-12 col-xs-12">
              <img src="{{ url_for('static', filename='images/norma.png') }}" style="height: 300px; width: 500px;" class="promo-section__img">
              <a href="https://www.youtube.com/watch?v=nVzVohG304A?autoplay=1" class="play-btn play-btn--center icon-wave single-video-lightbox"></a>
            </div>
            <div class="col-md-5 col-md-offset-1 col-sm-12">
              <div class="promo-section__description">
                <h2 class="promo-section__title">{{ config.SECTION_THREE_TITLE }}</h2>
                <p class="lead">{{ config.SECTION_THREE_INFO }}</p>
              </div>
            </div>
          </div>
        </div>
      </section> <!-- end promo section -->

      <!-- Promo Section -->
      <section class="section-wrap promo-section bottom-divider pb-100">
        <div class="container ">
          <div class="row flex-parent flex-vertical-align-center flex-sm-collapse">
            <div class="col-md-5 col-sm-12">
              <div class="promo-section__description">
                <h2 class="promo-section__title">{{ config.SECTION_FOUR_TITLE }}</h2>
                <p class="lead">{{ config.SECTION_FOUR_TITLE }}</p>
              </div>
            </div>
            <div class="col-md-6 col-md-offset-1 col-sm-12">
              <img src="{{ url_for('static', filename='img/promo/2.jpg') }}" alt="" class="promo-section__img">
            </div>
          </div>
        </div>
      </section> <!-- end promo section -->



      <!-- Feature -->
      <section class="section-wrap">
        <div class="container">
          <div class="row">

            <div class="col-sm-6 mb-sm-40">
              <div class="feature">
                <a href="#" class="feature__icon-holder">
                  <i class="ui-layers feature__icon feature__icon--gradient"></i>
                </a>
                <div class="feature__text">
                  <h3 class="feature__title">Well Documented</h3>
                  <p class="feature__paragraph feature__paragraph--padding-right">
                      All of Norman's features are well documented to make getting information and help available everytime.
                      The helpdesk is also available to provide help real time with a 99% response rate.
                  </p>
                </div>
              </div> <!-- end feature item -->
            </div>
              <div class="col-sm-6 mb-sm-40">
              <div class="feature">
                <a href="#" class="feature__icon-holder">
                  <i class="ui-layers feature__icon feature__icon--gradient"></i>
                </a>
                <div class="feature__text">
                  <h3 class="feature__title">Well Documented</h3>
                  <p class="feature__paragraph feature__paragraph--padding-right">
                      All of Norman's features are well documented to make getting information and help available everytime.
                      The helpdesk is also available to provide help real time with a 99% response rate.
                  </p>
                </div>
              </div> <!-- end feature item -->
            </div>

            <div class="col-sm-6">
              <div class="feature">
                <a href="#" class="feature__icon-holder">
                  <i class="ui-pencil-ruler feature__icon feature__icon--gradient"></i>
                </a>
                <div class="feature__text">
                  <h3 class="feature__title">Tracking and Securing Data</h3>
                  <p class="feature__paragraph feature__paragraph--padding-right">Norman tracks and secures your data in real time
                  as they come in. It then analyzes , carries out researches and  makes this data available for you in whatever format you might want it.</p>
                </div>
              </div> <!-- end feature item -->
            </div>

            <div class="col-sm-6">
              <div class="feature">
                <a href="#" class="feature__icon-holder">
                  <i class="ui-pencil-ruler feature__icon feature__icon--gradient"></i>
                </a>
                <div class="feature__text">
                  <h3 class="feature__title">Tracking and Securing Data</h3>
                  <p class="feature__paragraph feature__paragraph--padding-right">Norman tracks and secures your data in real time
                  as they come in. It then analyzes , carries out researches and  makes this data available for you in whatever format you might want it.</p>
                </div>
              </div> <!-- end feature item -->
            </div>

          </div>
        </div>
      </section> <!-- end feature -->
{% include 'shared/footer.html' %}

templates/shared/footer.html
      <!-- Footer -->
      <footer class="footer">
        <div class="container">
          <div class="footer__widgets">
            <div class="row">

              <div class="col-md-4 col-sm-3 col-xs-12">
                <div class="widget footer__about-us">
                  <img src="{{ url_for('static', filename='images/logo.png') }}" alt="" class="logo">
                  <div class="footer__socials mt-40">
                    <div class="social-icons social-icons--nobase">
                      <a href="#"><i class="ui-twitter"></i></a>
                      <a href="#"><i class="ui-facebook"></i></a>
                      <a href="#"><i class="ui-linkedin"></i></a>
                      <a href="#"><i class="ui-instagram"></i></a>
                    </div>
                  </div>
                </div>
              </div> <!-- end about us -->


              <div class="col-md-2 col-md-offset-2 col-sm-3 col-xs-12">
                <div class="widget widget-links">
                  <h5 class="widget-title">Product</h5>
                  <ul class="list-no-dividers">
                            <li><a href="{{ url_for('product.collate') }}">Norman Collate</a></li>
                            <li><a href="{{ url_for('product.analytics') }}">Norman Analytics</a></li>
                            <li><a href="{{ url_for('product.ipatient') }}">Norman IPatient</a></li>
                            <li><a href="{{ url_for('product.idoctor') }}">Norman IDoctor</a></li>
                            <li><a href="{{ url_for('product.ihealth') }}">Norman IHealth</a></li>
                            <li><a href="{{ url_for('product.bot') }}">Norman Bot</a></li>
                  </ul>
                </div>
              </div>

              <div class="col-md-2 col-sm-3 col-xs-12">
                <div class="widget widget-links">
                  <h5 class="widget-title">Support</h5>
                  <ul class="list-no-dividers">
                    <li><a href="{{ url_for('public.knowledge') }}">Knowledge Base</a></li>
                    <li><a href="#">Help Center</a></li>
                    <li><a href="#">Support Policy</a></li>
                    <li><a href="{{ url_for('public.privacy') }}">Privacy Policy</a></li>
                    <li><a href="{{ url_for('public.faq') }}">F.A.Q</a></li>
                  </ul>
                </div>
              </div>
              <div class="col-md-2 col-sm-3 col-xs-12">
                <div class="widget widget-links">
                  <h5 class="widget-title">The Company</h5>
                  <ul class="list-no-dividers">
                    <li><a href="#">Team</a></li>
                    <li><a href="#">Careers</a></li>
                    <li><a href="#">Blog</a></li>
                    <li><a href="#">Contact</a></li>
                  </ul>
                </div>
              </div>

            </div>
          </div>
        </div> <!-- end container -->

        <div class="footer__bottom top-divider">
          <div class="container text-center">
            <span class="copyright">
              &copy; 2017 Norman
            </span>
          </div>
        </div> <!-- end footer bottom -->
      </footer> <!-- end footer -->


      <div id="back-to-top">
        <a href="#top"><i class="ui-arrow-up"></i></a>
      </div>

    </div> <!-- end content wrapper -->
  </main> <!-- end main wrapper -->


  <!-- jQuery Scripts -->
  <script type="text/javascript" src="{{ url_for('static', filename='landing/js/jquery.min.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='landing/js/bootstrap.min.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='landing/js/plugins.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='landing/js/scripts.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='landing/js/utils.js') }}"></script>

</body>

</html>

templates/shared/header.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{{ config.APP_NAME }}</title>

  <meta charset="utf-8">
  <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><![endif]-->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700%7CLato:300,400,400i,700" rel="stylesheet">

  <!-- Css -->
  <link rel="stylesheet" href="{{ url_for('static', filename='landing/css/bootstrap.min.css') }}" />
  <link rel="stylesheet" href="{{ url_for('static', filename='landing/css/font-icons.css') }}" />
  <link rel="stylesheet" href="{{ url_for('static', filename='landing/css/style.css') }}" />

</head>

<body>
  <main class="main-wrapper">

    <!-- Navigation -->
    <header class="nav nav--transparent">

      <div class="nav__holder" id="sticky-nav">
        <div class="container">
          <div class="flex-parent">

            <div class="nav__header clearfix">
              <!-- Logo -->
              <div class="logo-wrap">
                <a href="/" class="logo__link">
                  <img class="logo logo--dark" src="{{ url_for('static', filename='images/logo.png') }}"  style="height: 3000px;" alt="logo">
                  <img class="logo logo--light" src="{{ url_for('static', filename='images/logo.png') }}" style="height: 3000px;" alt="logo">
                </a>
              </div>

              <button type="button" class="nav__icon-toggle" id="nav__icon-toggle" data-toggle="collapse" data-target="#navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="nav__icon-toggle-bar"></span>
                <span class="nav__icon-toggle-bar"></span>
                <span class="nav__icon-toggle-bar"></span>
              </button>
            </div> <!-- end nav-header -->

            <nav id="navbar-collapse" class="nav__wrap collapse navbar-collapse">
              <ul class="nav__menu nav__menu--inline">
                  <li class="nav__dropdown active">
                      <a href="{{ url_for('product.products') }}">Products</a>
                      <i class="ui-arrow-down nav__dropdown-trigger"></i>
                        <ul class="nav__dropdown-menu">
                            <li class="nav__dropdown"><a href="{{ url_for('product.collate') }}">Norman Collate</a></li>
                            <li><a href="{{ url_for('product.analytics') }}">Norman Analytics</a></li>
                            <li><a href="{{ url_for('product.ihealth') }}">Norman IHealth</a></li>
                            <li><a href="{{ url_for('product.idoctor') }}">Norman IDoctor</a></li>
                            <li><a href="{{ url_for('product.ipatient') }}">Norman IPatient</a></li>
                            <li><a href="{{ url_for('product.bot') }}">Norman Bot</a></li>
                        </ul>
                  </li>
                <li>
                  <a href="{{ url_for('public.pricing') }}">Pricing</a>
                </li>
                      <li>
                        <a href="{{ url_for('public.pricing') }}">API</a>
                      </li>
                    <li>
                      <a href="{{ url_for('public.knowledge') }}">Knowledge Base</a>
                    </li>

              </ul> <!-- end menu -->

              <div class="nav__btn-holder">
                <a href="javascript:handleAjaxRoute('auth/login')"  class="btn btn--sm btn--color square"><span>Login</span></a>
                <a href="javascript:handleAjaxRoute('auth/register', {'source':'landingPage', 'request':'requestDemo'})" class="btn btn--sm btn--secondary-color square"><span>Request Demo</span></a>
              </div>
            </nav> <!-- end nav-wrap -->

          </div> <!-- end flex-parent -->
        </div> <!-- end container -->

      </div>
    </header> <!-- end navigation -->

templates/shared/nav.html
{##}
{#<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">#}
{#  <div class="container">#}
{##}
{#  <!-- Brand and toggle get grouped for better mobile display -->#}
{#  <div class="navbar-header">#}
{#    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">#}
{#      <span class="sr-only">Toggle navigation</span>#}
{#      <span class="icon-bar"></span>#}
{#      <span class="icon-bar"></span>#}
{#      <span class="icon-bar"></span>#}
{#    </button>#}
{#    <a class="navbar-brand" href="{{ url_for('public.home') }}">#}
{##}
{#      Norman#}
{##}
{#    </a>#}
{#  </div>#}
{#  <!-- Collect the nav links, forms, and other content for toggling -->#}
{#  <div class="collapse navbar-collapse navbar-ex1-collapse">#}
{#    <ul class="nav navbar-nav">#}
{#      <li><a href="{{ url_for('public.home') }}">Home</a></li>#}
{#      <li><a href="{{ url_for('public.about') }}">About</a></li>#}
{#    </ul>#}
{#    {% if current_user and current_user.is_authenticated %}#}
{#    <ul class="nav navbar-nav navbar-right">#}
{#        <li>#}
{#            <p class="navbar-text"><a class="navbar-link" href="{{ url_for('user.members') }}">Logged in as {{ current_user.username }}</a></p>#}
{#        </li>#}
{#        <li><a class="navbar-link" href="{{ url_for('public.logout') }}"><i class="fa fa-sign-out"></i></a></li>#}
{##}
{#    </ul>#}
{#    {% elif form %}#}
{#    <ul class="nav navbar-nav navbar-right">#}
{#      <li><a href="{{ url_for('public.register') }}">Create account</a></li>#}
{#    </ul>#}
{#    <form id="loginForm" method="POST" class="navbar-form form-inline navbar-right" action="/" role="login">#}
{#      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>#}
{#      <div class="form-group">#}
{#        {{ form.username(placeholder="Username", class_="form-control") }}#}
{#        {{ form.password(placeholder="Password", class_="form-control") }}#}
{#      </div>#}
{#      <button type="submit" class="btn btn-default">Log in</button>#}
{#    </form>#}
{#    {% endif %}#}
{#  </div><!-- /.navbar-collapse -->#}
{#  </div><!-- /.container -->#}
{#</nav>#}
{##}